name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .next/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('package-lock.json', 'next.config.js', 'tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Store Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            .next
            out

  lint:
    runs-on: ubuntu-20.04
    needs: setup-and-build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  test:
    runs-on: ubuntu-20.04
    needs: setup-and-build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test -- --coverage

      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov-report
